version: '3'

services:
    frontend:
        platform: linux/amd64
        command: sh -c "yarn install && yarn dev"
        build: ./frontend
        ports:
            - "8000:8000"
        volumes:
            - "./frontend:/app"
            - "./backend_storage:/storage_mounted_for_testing"
            - node_modules:/app/node_modules
        environment:
            - VITE_DEV_FEATURES=true
            - VITE_TAPP_ADMINS=${VITE_TAPP_ADMINS}
    backend:
        build: ./backend
        platform: linux/amd64
        volumes:
            - "./backend:/app"
            - "./pg_data:/backup"
            - "./backend_storage:/storage"
    db:
        volumes:
            - "./pg_data/db:/var/lib/postgresql/data"
    mailcatcher:
        image: rordi/docker-mailcatcher
        container_name: mailcatcher
        ports:
            - 1080:1080
            - 1025:1025

volumes:
    node_modules: